/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { Degen__factory } from "./Degen__factory";
export { DegenToken__factory } from "./DegenToken__factory";
